version: "3.8"

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: doatech
      MYSQL_DATABASE: doatech 
      MYSQL_USER: doatech
      MYSQL_PASSWORD: doatech
